### ISSUE TITLE
Gibberish output with `Llama-2-7b-chat-hf-q4f32_1`

### ISSUE THREAD

**Issue by beaufortfrancois** [mlc-ai/web-llm#356] opened 2024-04-03 07:09 UTC
Chrome Version: 125.0.6283.3
OS: ChromeOS
GPU: Intel(R) Graphics (ADL GT2) - Intel open-source Mesa driver: Mesa 23.3.0 (git-5cb3f1e4fa)
Dawn Backend: Vulkan

**What steps will reproduce the problem?**
1. Go to https://webllm.mlc.ai/#chat-demo
2. Select `Llama-2-7b-chat-hf-q4f32_1`
3. Enter `What color is the dress?`

**What is the expected result?**
Some text that at least makes sense.

**What happens instead?**
Some gibberish text appears.
DevTools JavaScript console contains the following logs:
```
llm_chat.ts:150 Using prefillChunkSize:  1024
llm_chat.ts:180 Using maxWindowLength:  4096
llm_chat.ts:202 Using Paged KVCache
15vkAllocateMemory failed with VK_ERROR_OUT_OF_DEVICE_MEMORY
    at CheckVkOOMThenSuccessImpl (..<URL>)

15vkAllocateMemory failed with VK_ERROR_OUT_OF_DEVICE_MEMORY
    at CheckVkOOMThenSuccessImpl (..<URL>)
```
Then I enter "What color is the dress?"
```
97[Invalid Buffer (unlabeled)] is invalid.
 - While validating entries[0] as a Buffer.
Expected entry layout: { type: BufferBindingType::Storage, hasDynamicOffset: 0, minBindingSize: 0 }
 - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

162[Invalid BindGroup (unlabeled)] is invalid.
 - While encoding [ComputePassEncoder (unlabeled)].SetBindGroup(0, [Invalid BindGroup (unlabeled)], 0, ...).

161[Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

97[Invalid Buffer (unlabeled)] is invalid.
 - While validating entries[0] as a Buffer.
Expected entry layout: { type: BufferBindingType::Storage, hasDynamicOffset: 0, minBindingSize: 0 }
 - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

65[Invalid Buffer (unlabeled)] is invalid.
 - While validating entries[0] as a Buffer.
Expected entry layout: { type: BufferBindingType::ReadOnlyStorage, hasDynamicOffset: 0, minBindingSize: 0 }
 - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

162[Invalid BindGroup (unlabeled)] is invalid.
 - While encoding [ComputePassEncoder (unlabeled)].SetBindGroup(0, [Invalid BindGroup (unlabeled)], 0, ...).

161[Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

65[Invalid Buffer (unlabeled)] is invalid.
 - While validating entries[0] as a Buffer.
Expected entry layout: { type: BufferBindingType::ReadOnlyStorage, hasDynamicOffset: 0, minBindingSize: 0 }
 - While validating [BindGroupDescriptor] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

WebGPU: too many warnings, no more warnings will be reported to the console for this GPUDevice.
/#chat-demo:1 WebGPU: too many warnings, no more warnings will be reported to the console for this GPUDevice.
```

**Note**
It does work properly with the following f16 variants: `Llama-2-7b-chat-hf-q4f16_1` and `Llama-2-7b-chat-hf-q4f16_1-1k`
I can reproduce with `Llama-2-13b-chat-hf-q4f16_1`

![image](https://github.com/mlc-ai/web-llm/assets/634478/2ea50e0b-302f-454e-8acd-7b0dcea34474)

**Comment by CharlieFRuan** [comment] 2024-04-03 19:00
Thanks for reporting the issue, this seems to be an out-of-memory issue (f32 KV cache, and 13b params); llama-2-7b-q4f32_1 requires roughly 9 GB, while 13b-q4f16_1 requires roughly 10 GB.

How much RAM does Intel(R) Graphics (ADL GT2) have? Is it 16 GB? It might be a bit hard to catch the OOM error as we've seen earlier in https://github.com/mlc-ai/web-llm/issues/209.

**Comment by beaufortfrancois** [comment] 2024-04-12 09:27
I think we should catch [GPU out-of-memory errors](https://gpuweb.github.io/gpuweb/#gpuoutofmemoryerror) like we tried previously in https://github.com/mlc-ai/web-llm/issues/209#issuecomment-1858684132. 

FYI I was not able to catch them with https://chromewebstore.google.com/detail/webgpu-dev-extension/gkeaijopdhfempknmaggbjbedicopjgm either @greggman.

**Comment by beaufortfrancois** [comment] 2024-04-12 13:12
FYI https://webgpureport.org says the integrated GPU memoryHeaps is `[ size: 8269717504, properties: DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT | HOST_UNCACHED | HOST_CACHED ]` which suggests, I believe, this ChromeOS device can use up to 7.7 Go of memory.

**Comment by beaufortfrancois** [comment] 2024-04-15 07:53
@CharlieFRuan Are out-of-memory errors captured somewhere? In WebLLM or Apache TVM?

**Comment by CharlieFRuan** [comment] 2024-04-15 16:41
I know TVM can capture OOM for other backends (e.g. for [Vulkan here](https://github.com/apache/tvm/blob/521465e6268ff50c441b6b7eea8eff8579dc6ff2/src/runtime/vulkan/vulkan_buffer.cc#L61)). I'm not too sure what would be the case for webgpu. I'll make another attempt this week; thanks for the pointers!

**Comment by beaufortfrancois** [comment] 2024-04-16 08:03
https://github.com/search?q=repo%3Aapache%2Ftvm+%22out-of-memory%22&type=code returns no results for me ;(

**Comment by tqchen** [comment] 2024-04-16 12:33
I think webllm would needs its own mechanism. There are a few things.

- First of all, check whether webgpu buffer creation can throw an error, or caught by error scope (based on our previous trial seems it is not always the case)
- One approach might be to have TVM's GPU adapter to track the buffer allocated/deallocated, and throw after it gets to a cap

**Comment by beaufortfrancois** [comment] 2024-04-22 07:27
@CharlieFRuan Did you have a chance to have a look at this?

**Comment by CharlieFRuan** [comment] 2024-04-22 17:14
@beaufortfrancois I tried to catch the error with `CreateBuffer()` by adding [popErrorScope()](https://www.w3.org/TR/webgpu/#dom-gpudevice-poperrorscope) in the three places this is called in https://github.com/apache/tvm/blob/main/web/src/webgpu.ts -- no luck with that.

So I instead added a 1024 context length version model for llama-2-7b-q4f32_1, and made them the default choices in the demo page. I also added a note about the `-1k` models (bottom of screenshot) via https://github.com/mlc-ai/web-llm/pull/377.

<img width="763" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/e241ced2-2e91-46a0-8fd9-6079ec240f16">

**Comment by beaufortfrancois** [comment] 2024-04-23 10:59
> @beaufortfrancois I tried to catch the error with `CreateBuffer()` by adding [popErrorScope()](https://www.w3.org/TR/webgpu/#dom-gpudevice-poperrorscope) in the three places this is called in https://github.com/apache/tvm/blob/main/web/src/webgpu.ts -- no luck with that.

According to https://github.com/mlc-ai/web-llm/issues/356#issue-2222088484 logs, it looks like errors happen when validating entries in createBindGroup(), not after createBuffer(). Does it help?

Did you try [uncapturederror](https://gpuweb.github.io/gpuweb/#eventdef-gpudevice-uncapturederror) as well?
```js
device.onuncapturederror = ({error}) => {
  console.log(error);
})
```
 
> So I instead added a 1024 context length version model for llama-2-7b-q4f32_1, and made them the default choices in the demo page. This lowers the VRAM for ~3GB for llama-2 q4f32. I also added a note about the `-1k` models (bottom of screenshot) via #377.
> 
> <img alt="image" width="763" src="https://private-user-images.githubusercontent.com/53290280/324550251-e241ced2-2e91-46a0-8fd9-6079ec240f16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njc0NTAsIm5iZiI6MTcxMzg2NzE1MCwicGF0aCI6Ii81MzI5MDI4MC8zMjQ1NTAyNTEtZTI0MWNlZDItMmU5MS00NmEwLThmZDktNjA3OWVjMjQwZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MGJhZmY5NzYyMGQ1NzcxNDJiMTI4MWRlYTk1NGNhYTYwYWZhZjliNGJmNjg5YjI5YzYwNDRhN2E2Zjg5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lfm02YzRi1ffLRwfz5WeaO5MdAOZb_XJtaB7HpYgjCY">

That's useful. Thanks!

**Comment by beaufortfrancois** [comment] 2024-05-02 05:40
(gentle ping)

**Comment by beaufortfrancois** [comment] 2024-05-13 09:58
@CharlieFRuan Did you have a chance to look at this?

**Comment by CharlieFRuan** [comment] 2024-05-14 05:43
Sorry for the delay, will take a look tonight

**Comment by CharlieFRuan** [comment] 2024-05-14 20:04
Quick update: it does seem that the error can be caught! Not sure if I did something wrong earlier or there are some updates on the webgpu side.

Since my laptop does not run into OOM for most models, to reproduce the error, I set [maxTotalSeqLen](https://github.com/mlc-ai/web-llm/blob/3379591964a1aaa546c335f9d072aa0b0df08d52/src/llm_chat.ts#L200) to an arbitrary large number `909600`, as opposed to default values like 4k or 1k, this forces the engine to allocate a very large KVCache. Not sure if this is equivalent to the behavior of loading a model that is too large for the device (but should be quite similar).

Upon finishing loading the model, the engine will allocate the KVCache, and I see:
<img width="981" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/002bdb73-7432-45f4-aab6-9603a89118e3">

This log corresponds to the `push` and `pop` of `ErrorScope` I added here in `tvm/web`: 
<img width="947" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/c13b43cf-456d-4456-8833-ff8a80bd6051">

Then upon ignoring the error and start chatting, we hit the uncaptured error you suggested:
<img width="988" alt="image" src="https://github.com/mlc-ai/web-llm/assets/53290280/40376e6c-f74c-417e-8ca5-ed8fce955cf6">

I will refine the handling and upstream the changes after verifying the errors can indeed be well-caught. Should have another update by the end of this week. Thank you so much for the help!

**Comment by CharlieFRuan** [comment] 2024-05-21 22:06
OOM errors in `createBuffer()` are now able to be caught in webllm npm 0.2.36 via https://github.com/mlc-ai/web-llm/pull/402. If `createBuffer()` does not suffice, will follow up with more error catching in tvmjs. Thanks!

Redeployed https://webllm.mlc.ai/ as well.

**Comment by beaufortfrancois** [comment] 2024-05-23 12:21
This improvement is so much better!
![image](https://github.com/mlc-ai/web-llm/assets/634478/ea72e3ac-8e46-4c2e-b576-d0422a3d2610)

**Comment by CharlieFRuan** [comment] 2024-06-04 19:26
Closing this issue as completed; feel free to open new ones if problems persist!

**Closed by CharlieFRuan** 2024-06-04 19:26 UTC
