### ISSUE TITLE
cannot read properties of undefined  - description

### ISSUE THREAD

**Issue by flatsiedatsie** [mlc-ai/web-llm#572] opened 2024-09-23 12:35 UTC
I'm trying the Phi3.5 vision demo, but got the error below.

<img width="464" alt="Screenshot 2024-09-23 at 14 22 43" src="https://github.com/user-attachments/assets/7145bda7-d89c-4a12-b5c5-1cea2d055208">

I proceeded to wrap that bit of code in `if(K.adapterInfo){    ...    }`

And then it started working.

- Macbookk Pro M1
- Brave browser

Another thing I then ran into: I'm not allowed to use relative image paths?

<img width="460" alt="Screenshot 2024-09-23 at 14 34 18" src="https://github.com/user-attachments/assets/0a323b5a-c789-4f62-a920-2e342d6d2469">

**Comment by flatsiedatsie** [comment] 2024-09-23 12:55
See also:

https://flatsiedatsie.github.io/web_llm_vision/

and

https://www.reddit.com/r/LocalLLaMA/comments/1fnjnkc/webllm_has_added_support_for_its_first_vision/

**Comment by CharlieFRuan** [comment] 2024-09-26 04:28
I haven't ran into this issue yet, but below are some info.

The adapterInfo is defined here: 
 https://github.com/tqchen/tvm/blob/412aec4e2df8f01ee15f3165d9f740af5190866d/web/src/webgpu.ts#L27-L31

The adapterInfo is populated here:
https://github.com/tqchen/tvm/blob/412aec4e2df8f01ee15f3165d9f740af5190866d/web/src/webgpu.ts#L119-L133

Specifically, `GPUAdapter.info` (i.e. the `adapterInfo`) is documented here: https://www.w3.org/TR/webgpu/#gpuadapter

I am not very sure why `info` could be `undefined`. Though there is indeed a related [API deprecation](https://developer.mozilla.org/en-US/docs/Web/API/GPUAdapter/requestAdapterInfo#browser_compatibility) from the WebGPU side, where we adjusted this way: https://github.com/apache/tvm/pull/17371

**Comment by CharlieFRuan** [comment] 2024-09-26 04:30
I wonder if it is because your browser still prefers `requestAdapterInfo()`. If not too inconvenient, could you try updating the browser or using a different browser to see if the same issue is observed? Thanks!

**Comment by flatsiedatsie** [comment] 2024-09-26 09:36
Sure, I'll give it a try.

**Comment by flatsiedatsie** [comment] 2024-09-26 11:10
I just found out this is now interfering with all WebLLM inference, not just the Vision model.

<img width="473" alt="Screenshot 2024-09-26 at 13 08 47" src="https://github.com/user-attachments/assets/7069b72d-a75d-4bd0-bda5-e3e11f516412">

**Comment by slash-under** [comment] 2024-09-26 19:29
This issue affects me as well on Thorium (Chromium) 124 and the proposed solution works for me. As far as the `GPUAdapter` reference goes, there are some missing members, including GPUAdapterInfo.

![image](https://github.com/user-attachments/assets/94a7b1fd-5198-44de-885f-a7da73d2b367)

**Comment by CharlieFRuan** [comment] 2024-09-26 19:30
Thanks for all the info, I'll fix it today

**Comment by CharlieFRuan** [comment] 2024-09-26 19:31
Though I believe using the latest chrome should fix it; but I'll make sure we are backward compatible

**Comment by slash-under** [comment] 2024-09-26 19:50
The issue persists with the latest Thorium (126) but it looks like there have been further releases upstream....

**Comment by CharlieFRuan** [comment] 2024-09-26 20:57
Thanks for the info, fix is under the way

**Comment by CharlieFRuan** [comment] 2024-09-26 21:17
0.2.70 should include the fix, please let me know whether it worked on your end, thank you!
- https://github.com/mlc-ai/web-llm/pull/581

**Comment by slash-under** [comment] 2024-09-27 03:25
the fix does not appear to work on my end, but this may be an unrelated bug.

The updated code is in the `index.js` file, see here: [index.js](https://gist.github.com/slash-under/05bb6781f7446a135bc142dde3108164)

**Comment by CharlieFRuan** [comment] 2024-09-27 03:38
Hmm what is the bug you are seeing?

**Comment by flatsiedatsie** [comment] 2024-09-27 04:59
Still seeing the same error:

<img width="385" alt="Screenshot 2024-09-27 at 06 58 27" src="https://github.com/user-attachments/assets/364ea956-a969-418d-93ad-fb1ace27194c">

**Comment by flatsiedatsie** [comment] 2024-09-27 05:28
Could it be that the CDN version doesn't always get updated properly?

https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm/+esm

<img width="475" alt="Screenshot 2024-09-27 at 07 28 28" src="https://github.com/user-attachments/assets/9533f264-e217-476c-8593-fda943634a15">

**Comment by CharlieFRuan** [comment] 2024-09-27 05:30
The CDN seems to take a bit to get updated. Perhaps you can try specify 0.2.70 specifically?

**Comment by flatsiedatsie** [comment] 2024-09-27 05:38
Thanks, that helped.

New error with V2.7:

<img width="378" alt="Screenshot 2024-09-27 at 07 37 35" src="https://github.com/user-attachments/assets/fa476db0-b0a2-45a4-bb55-924f74992021">

**Comment by CharlieFRuan** [comment] 2024-09-27 05:50
Which version of brave are you on? I'll try to reproduce on my end

**Comment by CharlieFRuan** [comment] 2024-09-27 06:00
Ahh I can reproduce on `[Version 1.65.133 Chromium: 124.0.6367.208 (Official Build) (arm64)`. Taking a look

**Comment by CharlieFRuan** [comment] 2024-09-27 06:40
Turns out I missed an `await`. `0.2.71` should fixed this thoroughly: https://github.com/mlc-ai/web-llm/pull/583

Apologies for the inconvenience!

**Comment by flatsiedatsie** [comment] 2024-09-27 06:55
Glad you found a bug! I just realized I wasn't on the latest version of Brave:

`Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)`

I've upgraded now, and the problem is gone, even without being on 0.2.71.

**Comment by CharlieFRuan** [comment] 2024-09-27 18:28
Glad the issue is solved! Will close this one. Feel free to reopen / open new ones if issues persist

**Closed by CharlieFRuan** 2024-09-27 18:28 UTC

**Comment by slash-under** [comment] 2024-09-27 19:15
it seems this also is how hardware issues are handled. If the GPU process dies a certain way, you may end up with this error upon reload.

**Comment by slash-under** [comment] 2024-09-27 19:18
![image](https://github.com/user-attachments/assets/d895f8d5-f146-4f9d-bd22-a2f016450e92)

the transformed code appears to be in the build, as well

**Comment by slash-under** [comment] 2024-09-27 19:21
it seems that the web worker is the issue, and it does not have the latest patch: 
![image](https://github.com/user-attachments/assets/b09285fa-58fd-41a3-bd8e-0d117ff2110f)

![image](https://github.com/user-attachments/assets/b8c05967-8e58-4b61-979b-f031dbe9bed2)

**Comment by CharlieFRuan** [comment] 2024-09-27 19:28
I wonder if it is because you need to clear some cached files. I feel like the `index.js` on npm is kind of the source of truth of the most updated code: https://www.npmjs.com/package/@mlc-ai/web-llm?activeTab=code

IIUC, the `const adapterInfo` line should appear only once, since WebWorker and non-WebWorker call on the same helper function implemented in TVMjs.

Perhaps do something like `rm -r lib/ node_modules/ dist/ .parcel-cache` and re-do `npm install` and `npm run build`

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/9376f705-cf26-40ec-82a8-ae27bdd0e8e8">

**Comment by slash-under** [comment] 2024-09-27 19:31
I removed `.next/` and things worked after

**Comment by CharlieFRuan** [comment] 2024-09-27 19:33
I see! Glad it worked!
